# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra", "4.2.0"

group :development do
  gem "pry"
end

group :test do
  gem "rspec"
end

group :development, :test do
  gem "capybara"
end
